"""Email dispatch via SMTP with SSL/TLS and dry-run support.

EARS coverage
─────────────
- Ubiquitous 2.1-4: format final digest as HTML/plaintext email.
- Event 2.2-4: dispatch email to configured recipient after LLM summary.
- State 2.3-2: use encrypted SSL/TLS for SMTP connections.
- State 2.3-3: in dry-run mode, print email to console instead of sending.
"""

from __future__ import annotations

import logging
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import TYPE_CHECKING

import mistune
from jinja2 import Environment, select_autoescape
from markupsafe import Markup

from digest_pipeline.config import Settings

if TYPE_CHECKING:
    from digest_pipeline.hf_fetcher import HFDailyPaper
    from digest_pipeline.pipeline import PaperAnalysis

logger = logging.getLogger(__name__)

_md = mistune.create_markdown()


def _markdown_to_html(text: str) -> Markup:
    """Convert markdown text to HTML, marked safe for Jinja2 auto-escaping."""
    return Markup(_md(text))


_html_env = Environment(autoescape=select_autoescape(default=True))
_html_env.filters["md"] = _markdown_to_html

HTML_TEMPLATE = _html_env.from_string("""\
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
         max-width: 700px; margin: auto; padding: 20px; color: #222; }
  h1 { color: #1a1a2e; border-bottom: 2px solid #e2e2e2; padding-bottom: 10px; }
  h2 { color: #2d2d44; margin-top: 30px; }
  h2 a { color: #2d2d44; text-decoration: none; }
  h2 a:hover { text-decoration: underline; }
  h3 { color: #444; margin-top: 18px; margin-bottom: 6px; }
  .authors { color: #666; font-size: 0.9em; margin-top: 2px; }
  .categories { color: #888; font-size: 0.85em; margin-top: 2px; }
  .source-badge { display: inline-block; font-size: 0.75em; padding: 2px 8px;
                  border-radius: 4px; background: #e8e8f0; color: #555;
                  margin-top: 4px; }
  .section { line-height: 1.6; }
  .paper { margin-bottom: 10px; }
  hr { border: none; border-top: 1px solid #e2e2e2; margin: 30px 0; }
  .trending { margin-top: 30px; padding: 16px; background: #f8f8fc;
              border-radius: 6px; border-left: 3px solid #6c5ce7; }
  .trending h2 { color: #6c5ce7; margin-top: 0; font-size: 1.1em; }
  .trending ul { margin: 8px 0; padding-left: 20px; }
  .trending li { margin-bottom: 6px; }
  .trending .upvotes { color: #888; font-size: 0.85em; }
  .footer { margin-top: 30px; font-size: 0.85em; color: #888; }
</style></head>
<body>
  <h1>Daily Research Digest &mdash; {{ date }}</h1>
  {% for paper in papers %}
  <div class="paper">
    <h2><a href="{{ paper.url }}">{{ paper.title }}</a></h2>
    <p class="authors">{{ paper.authors | join(', ') }}</p>
    <span class="source-badge">{{ paper.source }}</span>
    {% if paper.categories %}
    <p class="categories">{{ paper.categories | join(' · ') }}</p>
    {% endif %}
    {% if paper.summary %}
    <h3>Summary</h3>
    <div class="section">{{ paper.summary | md }}</div>
    {% endif %}
    {% if paper.implications %}
    <h3>Practical Implications</h3>
    <div class="section">{{ paper.implications | md }}</div>
    {% endif %}
    {% if paper.critique %}
    <h3>Critique</h3>
    <div class="section">{{ paper.critique | md }}</div>
    {% endif %}
  </div>
  {% if not loop.last %}<hr>{% endif %}
  {% endfor %}
  {% if hf_trending %}
  <div class="trending">
    <h2>Trending on HuggingFace</h2>
    <p style="font-size: 0.9em; color: #666;">These papers from your digest are also trending in the HuggingFace community.</p>
    <ul>
    {% for t in hf_trending %}
      <li><a href="{{ t.url }}">{{ t.title }}</a> <span class="upvotes">({{ t.upvotes }} upvotes)</span></li>
    {% endfor %}
    </ul>
  </div>
  {% endif %}
  <p class="footer">Generated by the Automated Research Digest Pipeline.
     {{ papers | length }} paper(s) processed.</p>
</body>
</html>
""")

_plain_env = Environment(autoescape=False)
PLAIN_TEMPLATE = _plain_env.from_string("""\
Daily Research Digest — {{ date }}
==========================================
{% for paper in papers %}

## {{ paper.title }}
{{ paper.url }}
Authors: {{ paper.authors | join(', ') }}
Source: {{ paper.source }}
{% if paper.categories %}
Categories: {{ paper.categories | join(', ') }}
{% endif %}
{% if paper.summary %}

### Summary

{{ paper.summary }}
{% endif %}
{% if paper.implications %}

### Practical Implications

{{ paper.implications }}
{% endif %}
{% if paper.critique %}

### Critique

{{ paper.critique }}
{% endif %}
{% if not loop.last %}

---
{% endif %}
{% endfor %}
{% if hf_trending %}

---
## Trending on HuggingFace

These papers from your digest are also trending in the HuggingFace community.
{% for t in hf_trending %}
- {{ t.title }} ({{ t.upvotes }} upvotes)
  {{ t.url }}
{% endfor %}
{% endif %}

---
Generated by the Automated Research Digest Pipeline.
{{ papers | length }} paper(s) processed.
""")


def _build_email(
    papers: list[PaperAnalysis],
    date_str: str,
    settings: Settings,
    hf_trending: list[HFDailyPaper] | None = None,
) -> MIMEMultipart:
    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"Research Digest — {date_str}"
    msg["From"] = settings.email_from
    msg["To"] = settings.email_to

    ctx: dict = {"papers": papers, "date": date_str, "hf_trending": hf_trending or []}
    msg.attach(MIMEText(PLAIN_TEMPLATE.render(**ctx), "plain"))
    msg.attach(MIMEText(HTML_TEMPLATE.render(**ctx), "html"))
    return msg


def send_digest(
    papers: list[PaperAnalysis],
    date_str: str,
    settings: Settings,
    hf_trending: list[HFDailyPaper] | None = None,
) -> None:
    """Format and send (or print) the daily digest email.

    *hf_trending* is an optional list of HuggingFace papers that overlap
    with the arXiv set — rendered as a "Trending on HuggingFace" sidebar.

    In dry-run mode the email payload is printed to the console instead
    of being sent (EARS 2.3-3).
    """
    msg = _build_email(papers, date_str, settings, hf_trending=hf_trending)

    if settings.dry_run:
        logger.info("DRY-RUN mode — printing email to console.")
        print("=" * 60)
        print(f"To:      {settings.email_to}")
        print(f"From:    {settings.email_from}")
        print(f"Subject: {msg['Subject']}")
        print("=" * 60)
        ctx: dict = {"papers": papers, "date": date_str, "hf_trending": hf_trending or []}
        print(PLAIN_TEMPLATE.render(**ctx))
        print("=" * 60)
        return

    logger.info("Sending digest email via %s:%d.", settings.smtp_host, settings.smtp_port)
    server = smtplib.SMTP(settings.smtp_host, settings.smtp_port)
    server.starttls()
    with server:
        server.login(settings.smtp_user, settings.smtp_password)
        server.send_message(msg)
    logger.info("Email sent to %s.", settings.email_to)
